### ISSUE TITLE
License

### ISSUE THREAD

**Issue by nmfisher** [postech-ami/MultiTalk#1]
What license are you releasing the code in this repository under?

**Comment by chae0382** [comment]
Hi @nmfisher , thanks for your interest in our work! 

Please refer to the [agreement](https://github.com/postech-ami/MultiTalk/blob/main/README.md#agreement) in the readme.
We do not hold the rights to any of these videos, thus please follow the youtube license guidelines.

**Comment by nmfisher** [comment]
@chae0382 Thanks for the response! I was actually asking about the code and pretrained models though - e.g. could I copy some of your code to use with my own dataset?

**Comment by chae0382** [comment]
Free feel to use our code and pretrained models in this repository :)
Thanks.

**Comment by nmfisher** [comment]
> Free feel to use our code and pretrained models in this repository :) Thanks.

Great - can I suggest adding a LICENCE file to the repository to make it clear? Thanks again!
